"""
agent_core/agent_core_gateway.py — Bedrock AgentCore gateway that exposes the
telco REST API as an MCP server.

Following the project convention, ALL AgentCore constructs (gateways,
runtimes, targets) live under `agent_core/`. This module mirrors the method
layout of the reference `agentcore-gateway-primitive`:

    create_role()              — the execution role the gateway assumes
    create_gateway(...)        — the CfnGateway with its inbound authorizer
    add_openapi_inline_target()— an inline OpenAPI target (authored spec, API-key cred)
    _patch_audience_to_self()  — UpdateGateway custom resource that sets
                                 allowedAudience to the gateway's own id

Only two L1 resources exist for this in aws_cdk.aws_bedrockagentcore:
`CfnGateway` and `CfnGatewayTarget`.

Inbound authorization (identity provider)
-----------------------------------------
The gateway trusts JWTs whose issuer is discovered from the Connect
instance's OpenID configuration:

    https://<instance-alias>.my.connect.aws/.well-known/openid-configuration

Allowed audience — the circular-dependency problem and the two solutions
-----------------------------------------------------------------------
Amazon Connect issues the inbound JWT with `aud = <gateway id>` (confirmed
against the reference gateway, whose allowedAudience is its own full id).
But the gateway id is generated by AWS at create time, so it cannot be an
INPUT to the same CfnGateway resource that produces it — CloudFormation
would see a circular dependency.

This construct resolves that in a single deploy: create the gateway with a
placeholder audience (the gateway NAME), then an AwsCustomResource calls
bedrock-agentcore-control:UpdateGateway to set
allowedAudience = [<gateway id>] once the id exists. One `cdk deploy`,
works in a fresh account where the id isn't known up front.

UpdateGateway is a FULL-REPLACE update: it requires name, roleArn,
authorizerType and the COMPLETE authorizerConfiguration to be re-sent, not
just the changed field — so the custom resource re-sends all of them.
"""

from __future__ import annotations

from aws_cdk import Fn, Stack
from aws_cdk import aws_bedrockagentcore as bedrockagentcore
from aws_cdk import aws_iam as iam
from aws_cdk import custom_resources as cr
from constructs import Construct


class AgentCoreGateway(Construct):
    """AgentCore MCP gateway fronting the telco REST API."""

    def __init__(
        self,
        scope: Construct,
        construct_id: str,
        *,
        name: str,
        discovery_url: str,
        description: str = "",
        **kwargs,
    ) -> None:
        super().__init__(scope, construct_id, **kwargs)
        self._name = name
        self._discovery_url = discovery_url
        self._description = description

        # The gateway is created with the NAME as a placeholder audience; an
        # UpdateGateway custom resource then patches allowedAudience to the
        # gateway's real id (which only exists after create). See
        # _patch_audience_to_self.
        self._audience = name

        self.create_gateway(name, description)
        self._patch_audience_to_self()

    # ------------------------------------------------------------------ #
    # Role
    # ------------------------------------------------------------------ #
    def create_role(self) -> None:
        stk = Stack.of(self)
        region = stk.region
        account_id = stk.account

        self.role = iam.Role(
            self,
            "BedrockGatewayRole",
            assumed_by=iam.ServicePrincipal(
                service="bedrock-agentcore.amazonaws.com",
                conditions={
                    "StringEquals": {"aws:SourceAccount": account_id},
                    "ArnLike": {
                        "aws:SourceArn": f"arn:aws:bedrock-agentcore:{region}:{account_id}:*"
                    },
                },
            ),  # type: ignore[arg-type]
            description="Role the AgentCore gateway assumes to invoke its targets.",
        )
        self.role.add_to_policy(
            iam.PolicyStatement(
                actions=[
                    "bedrock-agentcore:*",
                    "bedrock:*",
                    "agent-credential-provider:*",
                    "iam:PassRole",
                    "secretsmanager:GetSecretValue",
                    "execute-api:Invoke",
                ],
                resources=["*"],
            )
        )

    # ------------------------------------------------------------------ #
    # Gateway
    # ------------------------------------------------------------------ #
    def create_gateway(self, name: str, description: str = "") -> None:
        self.create_role()

        self.gateway = bedrockagentcore.CfnGateway(
            self,
            "Gateway",
            name=name,
            protocol_type="MCP",
            role_arn=self.role.role_arn,
            authorizer_type="CUSTOM_JWT",
            authorizer_configuration=bedrockagentcore.CfnGateway.AuthorizerConfigurationProperty(
                custom_jwt_authorizer=bedrockagentcore.CfnGateway.CustomJWTAuthorizerConfigurationProperty(
                    discovery_url=self._discovery_url,
                    allowed_audience=[self._audience],
                )
            ),
            description=description,
        )
        self.gateway.node.add_dependency(self.role)

    # ------------------------------------------------------------------ #
    # Auto-audience: patch allowedAudience to the gateway's own id
    # ------------------------------------------------------------------ #
    def _patch_audience_to_self(self) -> None:
        """
        Single-deploy resolution of the audience-equals-own-id circularity.

        After the gateway exists, call UpdateGateway to set
        allowedAudience = [<gateway id>]. UpdateGateway is a full-replace
        update, so name / roleArn / authorizerType / the complete
        authorizerConfiguration are all re-sent. The gateway id is available
        as `attr_gateway_identifier` once the CfnGateway is created, so it is
        a valid INPUT to a downstream resource (no circular dependency).
        """
        gateway_id = self.gateway.attr_gateway_identifier

        update_params = {
            "gatewayIdentifier": gateway_id,
            "name": self._name,
            "roleArn": self.role.role_arn,
            "protocolType": "MCP",
            "authorizerType": "CUSTOM_JWT",
            "authorizerConfiguration": {
                "customJWTAuthorizer": {
                    "discoveryUrl": self._discovery_url,
                    # The whole point: audience = the gateway's own id.
                    "allowedAudience": [gateway_id],
                }
            },
        }
        if self._description:
            update_params["description"] = self._description

        self.audience_patch = cr.AwsCustomResource(
            self,
            "AudiencePatch",
            # The default Lambda runtime SDK is too old to know the
            # bedrock-agentcore-control UpdateGateway shape and silently drops
            # the authorizerConfiguration (so allowedAudience never changes and
            # the gateway keeps the placeholder NAME as its audience). Force the
            # latest SDK so the allowedAudience=[<gateway id>] update is honored.
            # (Same gotcha as ApiKeyCredentialProvider.)
            install_latest_aws_sdk=True,
            on_create=cr.AwsSdkCall(
                service="bedrock-agentcore-control",
                action="updateGateway",
                parameters=update_params,
                # A stable physical id tied to this gateway so the resource is
                # not recreated on every deploy.
                physical_resource_id=cr.PhysicalResourceId.of(
                    f"audience-patch-{gateway_id}"
                ),
            ),
            on_update=cr.AwsSdkCall(
                service="bedrock-agentcore-control",
                action="updateGateway",
                parameters=update_params,
                physical_resource_id=cr.PhysicalResourceId.of(
                    f"audience-patch-{gateway_id}"
                ),
            ),
            # No on_delete: tearing down the gateway (CfnGateway) removes it;
            # there is nothing to undo on the audience itself.
            policy=cr.AwsCustomResourcePolicy.from_statements(
                [
                    iam.PolicyStatement(
                        actions=["bedrock-agentcore:UpdateGateway"],
                        resources=["*"],
                    ),
                    # UpdateGateway re-sends roleArn, so the custom resource's
                    # role must be allowed to pass it to the service.
                    iam.PolicyStatement(
                        actions=["iam:PassRole"],
                        resources=[self.role.role_arn],
                    ),
                ]
            ),
        )
        # The patch must run after the gateway exists.
        self.audience_patch.node.add_dependency(self.gateway)

    # ------------------------------------------------------------------ #
    # Inline OpenAPI target (rich, authored spec)
    # ------------------------------------------------------------------ #
    def add_openapi_inline_target(
        self,
        target_name: str,
        *,
        spec_json_template: str,
        rest_api_id: str,
        stage: str,
        api_key_provider_arn: str,
        api_key_header_name: str = "x-api-key",
        description: str = "",
    ) -> bedrockagentcore.CfnGatewayTarget:
        """
        Add a target whose tool surface comes from a rich, authored OpenAPI
        document embedded INLINE (open_api_schema.inline_payload), instead of
        the schema API Gateway auto-exports.

        `spec_json_template` is the authored spec serialized to a JSON string
        whose server URL still contains the ${ApiId} / ${Stage} markers (see
        apis/openapi_spec.render_spec_json). We wrap it in Fn.sub here so those
        markers resolve, at deploy time, to the REAL deployed REST API id and
        stage — guaranteeing the inline spec's server URL matches the live API.
        ${AWS::Region} resolves automatically as a CloudFormation
        pseudo-parameter.

        OpenAPI-schema targets REQUIRE an explicit credential provider. Here we
        wire an API KEY credential provider: AgentCore injects the stored key
        into `api_key_header_name` on each call to the backend API. The
        provider ARN comes from an ApiKeyCredentialProvider custom resource.

        Tool names/descriptions/IO come straight from the authored spec, so no
        tool_overrides are needed here.
        """
        rendered_payload = Fn.sub(
            spec_json_template,
            {
                "ApiId": rest_api_id,
                "Stage": stage,
            },
        )

        target = bedrockagentcore.CfnGatewayTarget(
            self,
            f"Target-{target_name}",
            name=target_name.replace("_", "-") + "-target",
            gateway_identifier=self.gateway.attr_gateway_identifier,
            credential_provider_configurations=[
                bedrockagentcore.CfnGatewayTarget.CredentialProviderConfigurationProperty(
                    credential_provider_type="API_KEY",
                    credential_provider=bedrockagentcore.CfnGatewayTarget.CredentialProviderProperty(
                        api_key_credential_provider=bedrockagentcore.CfnGatewayTarget.ApiKeyCredentialProviderProperty(
                            provider_arn=api_key_provider_arn,
                            # Send the key as a header named api_key_header_name
                            # (API Gateway expects the API key in x-api-key).
                            credential_location="HEADER",
                            credential_parameter_name=api_key_header_name,
                        )
                    ),
                )
            ],
            target_configuration=bedrockagentcore.CfnGatewayTarget.TargetConfigurationProperty(
                mcp=bedrockagentcore.CfnGatewayTarget.McpTargetConfigurationProperty(
                    open_api_schema=bedrockagentcore.CfnGatewayTarget.ApiSchemaConfigurationProperty(
                        inline_payload=rendered_payload,
                    )
                )
            ),
            description=description[:200],
        )
        target.node.add_dependency(self.gateway)
        return target
    @property
    def gateway_id(self) -> str:
        """Generated gateway id — the value Connect should use as JWT audience."""
        return self.gateway.attr_gateway_identifier

    @property
    def gateway_url(self) -> str:
        """The MCP endpoint URL clients connect to."""
        return self.gateway.attr_gateway_url
